-   id: kustomize
    name: kustomize (via docker)
    description: kustomize
    entry: run.sh
    language: docker
    args: [clusters/nonprod/overlays/dev]
    always_run: true
    pass_filenames: false
